name: Pricing_Intelligence
services:
  choco-api:
    build:
      context: .
      dockerfile: csp/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
  analysis-api:
    build:
      context: ./analysis_api
      dockerfile: Dockerfile
    ports:
      - "8002:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CHOCO_API=http://choco-api:8000
      - LOG_LEVEL=INFO
    volumes:
      - ./analysis_api/src:/app/src
      - ./analysis_api/logs:/app/logs
      - ./analysis_api/output:/app/output
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - choco-api
    restart: unless-stopped
  a-mint-api:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8001:8000"
    environment:
      - PYTHONPATH=/app
      - PORT=8000
      - OPENAI_API_KEY=${AMINT_API_KEY}
      - OPENAI_API_KEYS=${AMINT_API_KEYS}
      - ANALYSIS_API=http://analysis-api:3000/api/v1
      - LOG_LEVEL=INFO
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./output:/app/output
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    depends_on:
      - analysis-api
  mcp-server:
    build:
      context: ./mcp_server
      dockerfile: Dockerfile
    environment:
      - AMINT_BASE_URL=http://a-mint-api:8000
      - ANALYSIS_BASE_URL=http://analysis-api:3000
      - HARVEY_BASE_URL=http://harvey-api:8086
      - CACHE_BACKEND=memory
      - LOG_LEVEL=INFO
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=8085
    ports:
      - "8085:8085"
    depends_on:
      - a-mint-api
      - analysis-api
    restart: unless-stopped
  harvey-api:
    build:
      context: .
      dockerfile: harvey_api/Dockerfile
    ports:
      - "8086:8086"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8086
      - LOG_LEVEL=INFO
      - OPENAI_API_KEY=${HARVEY_API_KEY}
      - OPENAI_MODEL=gemini-2.5-flash
      - OPENAI_BASE_URL=https://generativelanguage.googleapis.com/v1beta/openai/
      - AMINT_BASE_URL=http://a-mint-api:8000
      - ANALYSIS_BASE_URL=http://analysis-api:3000
      - CACHE_BACKEND=memory
      - MCP_TRANSPORT=stdio
    depends_on:
      - a-mint-api
      - analysis-api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
  mcp-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:8086
        - VITE_SPHERE_BASE_URL=https://sphere.score.us.es
    environment:
      NODE_ENV: development
    ports:
      - "80:80"
    depends_on:
      - harvey-api
    restart: unless-stopped
